
/**************************************************************
 *	
 *	AxeSFX, 8 bit, 11025Hz,
 *	1 channel, 5888 bytes/channel
 *	Total Size: 1 * 5888 + 4 (header) = 5932 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\M04\AxeSFX.wav
 *	Time-stamp: Thu Apr 18 04:06:42 2019
 *	
 **************************************************************/

#ifndef __AXESFXH__
#define __AXESFXH__

#define AXESFXFREQ 11025
#define AXESFXLEN 5888

extern const unsigned char AxeSFX[5888];

#endif /* __AXESFXH__ */
