
/**************************************************************
 *	
 *	CheatSFX, 8 bit, 11025Hz,
 *	1 channel, 14928 bytes/channel
 *	Total Size: 1 * 14928 + 4 (header) = 14972 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\Real Final\CheatSFX.wav
 *	Time-stamp: Mon Apr 22 12:06:57 2019
 *	
 **************************************************************/

#ifndef __CHEATSFXH__
#define __CHEATSFXH__

#define CHEATSFXFREQ 11025
#define CHEATSFXLEN 14928

extern const unsigned char CheatSFX[14928];

#endif /* __CHEATSFXH__ */
