
/**************************************************************
 *	
 *	CoinSFX, 8 bit, 11025Hz,
 *	1 channel, 4973 bytes/channel
 *	Total Size: 1 * 4973 + 4 (header) = 5017 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\M04\CoinSFX.wav
 *	Time-stamp: Thu Apr 18 04:08:23 2019
 *	
 **************************************************************/

#ifndef __COINSFXH__
#define __COINSFXH__

#define COINSFXFREQ 11025
#define COINSFXLEN 4973

extern const unsigned char CoinSFX[4973];

#endif /* __COINSFXH__ */
