
/**************************************************************
 *	
 *	DeathSFX, 8 bit, 11025Hz,
 *	1 channel, 8320 bytes/channel
 *	Total Size: 1 * 8320 + 4 (header) = 8364 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\Real Final\DeathSFX.wav
 *	Time-stamp: Mon Apr 22 12:26:53 2019
 *	
 **************************************************************/

#ifndef __DEATHSFXH__
#define __DEATHSFXH__

#define DEATHSFXFREQ 11025
#define DEATHSFXLEN 8320

extern const unsigned char DeathSFX[8320];

#endif /* __DEATHSFXH__ */
