
/**************************************************************
 *	
 *	GameMusic, 8 bit, 11025Hz,
 *	1 channel, 1124352 bytes/channel
 *	Total Size: 1 * 1124352 + 4 (header) = 1124396 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\M04\GameMusic.wav
 *	Time-stamp: Thu Apr 18 03:46:33 2019
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 1124352

extern const unsigned char GameMusic[1124352];

#endif /* __GAMEMUSICH__ */
