
/**************************************************************
 *	
 *	GoblinSFX, 8 bit, 11025Hz,
 *	1 channel, 10411 bytes/channel
 *	Total Size: 1 * 10411 + 4 (header) = 10455 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\Real Final\GoblinSFX.wav
 *	Time-stamp: Mon Apr 22 12:39:46 2019
 *	
 **************************************************************/

#ifndef __GOBLINSFXH__
#define __GOBLINSFXH__

#define GOBLINSFXFREQ 11025
#define GOBLINSFXLEN 10411

extern const unsigned char GoblinSFX[10411];

#endif /* __GOBLINSFXH__ */
