
/**************************************************************
 *	
 *	QueenSFX, 8 bit, 11025Hz,
 *	1 channel, 44641 bytes/channel
 *	Total Size: 1 * 44641 + 4 (header) = 44685 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\M04\QueenSFX.wav
 *	Time-stamp: Thu Apr 18 04:17:23 2019
 *	
 **************************************************************/

#ifndef __QUEENSFXH__
#define __QUEENSFXH__

#define QUEENSFXFREQ 11025
#define QUEENSFXLEN 44641

extern const unsigned char QueenSFX[44641];

#endif /* __QUEENSFXH__ */
