
/**************************************************************
 *	
 *	ScreenMusic, 8 bit, 11025Hz,
 *	1 channel, 1477152 bytes/channel
 *	Total Size: 1 * 1477152 + 4 (header) = 1477196 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\M04\ScreenMusic.wav
 *	Time-stamp: Thu Apr 18 03:32:31 2019
 *	
 **************************************************************/

#ifndef __SCREENMUSICH__
#define __SCREENMUSICH__

#define SCREENMUSICFREQ 11025
#define SCREENMUSICLEN 1477152

extern const unsigned char ScreenMusic[1477152];

#endif /* __SCREENMUSICH__ */
