
/**************************************************************
 *	
 *	TheftSFX, 8 bit, 11025Hz,
 *	1 channel, 1588 bytes/channel
 *	Total Size: 1 * 1588 + 4 (header) = 1632 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sabrina\Desktop\Spring2019\cs2261\Final Project\Real Final\TheftSFX.wav
 *	Time-stamp: Mon Apr 22 13:02:46 2019
 *	
 **************************************************************/

#ifndef __THEFTSFXH__
#define __THEFTSFXH__

#define THEFTSFXFREQ 11025
#define THEFTSFXLEN 1588

extern const unsigned char TheftSFX[1588];

#endif /* __THEFTSFXH__ */
